import { ElementRef, EventEmitter, OnInit } from '@angular/core';
import 'pdfjs-dist/build/pdf.combined';
import 'pdfjs-dist/web/pdf_viewer';
export declare class PdfViewerComponent extends OnInit {
    private element;
    private static CSS_UNITS;
    private _showAll;
    private _renderText;
    private _renderAnnotation;
    private _originalSize;
    private _src;
    private _pdf;
    private _page;
    private _zoom;
    private wasInvalidPage;
    private _rotation;
    private isInitialised;
    private lastLoaded;
    private _pageViews;
    afterLoadComplete: Function;
    constructor(element: ElementRef);
    ngOnInit(): void;
    src: any;
    page: any;
    pageChange: EventEmitter<number>;
    renderText: any;
    renderAnnotation: any;
    originalSize: boolean;
    showAll: boolean;
    zoom: number;
    rotation: number;
    private main();
    private loadPDF(src);
    private onRender();
    private renderMultiplePages();
    private isValidPageNumber(page);
    private renderPage(pageNumber);
    private removeAllChildNodes(element);
    refreshSize(): void;
}
